Django_editor_backend/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('V1/course/', include('courseApp.urls')),
    path(r'V1/editor/', include('online_editor.urls')),
    path(r'V1/user/', include('identity.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Access uploaded photos

courseApp/urls.py
from django.urls import path
from . import views

app_name = 'courseApp'

urlpatterns = [
    path('topicsByTeacher/', views.TopicsByTeacher, name='TopicsByTeacher'),
    path('courses/<str:topic_title>/', views.Courses, name='Courses'),
    path('courseDetail/<str:topic_title>/<int:id>/', views.coursesDetail, name='coursesDetail'),
    path('search/', views.search, name='search'),
    path('search/<str:keyword>', views.search_topic),
    path('topic/<str:num>', views.top_topic),
    path('newtopic/', views.new_topic),
    path('binlog/', views.binlog),
    path('binlogs/', views.lastModifiedBinlog),
    path('create/', views.create),
    path('edit/', views.edit),
    path('sort/', views.sort),
    path('delete/', views.delete),
    path('upload_topic_img/', views.upload_topic_img),
    path('upload_course_img/<str:topic_title>/', views.upload_course_img),
    path('delete_img/', views.delete_img),
    path('add_user_progress/', views.add_user_courses_progress),
    path('change_user_progress/', views.user_change_course_progress),
    path('remove_user_progress/', views.remove_user_progress),
    path('add_user_collection/', views.add_user_collection),
    path('delete_user_collection/', views.delete_user_collection)
]

identity/urls.py
# -*- coding = utf-8 -*-
# @Time : 2021-07-26 17:35
# @Author : Danny
# @File : urls.py
# @Software: PyCharm

from django.urls import path
from identity import views
from django.conf.urls import include


app_name = 'identity'
urlpatterns = [
    path('register/', views.user_register),
    path('login/', views.user_login),
    path('logout/', views.user_logout),
    path('currentuser/', views.current_user),
    path('change_password/', views.change_user_password),
    path('icon/', views.edit_usericon),
    path('edit_userInfo/', views.edit_userInfo),
    path('send_verification_email/', views.send_verify_email),
    path('user_course_progress/', views.user_course_progress),
    path('updateTag/', views.updateTag)
]

courseApp/models.py
"""
课程数据库模型
"""
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from identity.models import Admin


class Topic(models.Model):
    topic_title = models.CharField(max_length=20, verbose_name='Topic title')  # Topic title
    topic_id = models.AutoField(primary_key=True, auto_created=True)
    teacher = models.ForeignKey(to=Admin, on_delete=models.CASCADE)
    topic_description = models.TextField(max_length=200, default="")  # A brief description of the content
    topic_content = models.TextField(null=True)  # introduction to the main content of the topic
    views = models.PositiveIntegerField('浏览量', default=0)  # view numbers of the topic
    create_time = models.DateTimeField(auto_now=True)
    topic_img = models.ImageField(null=True, blank=True, verbose_name='topic_image', upload_to="topic_imgs/")

    def __str__(self):
        return self.topic_title


class MyCourse(models.Model):
    id = models.AutoField(primary_key=True, max_length=20, auto_created=True, unique=True)
    content = RichTextUploadingField(u'内容', default='请输入课程内容')
    related_topic = models.ForeignKey(to=Topic, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, verbose_name='课程标题')  # 和subtopic_title
    update_date = models.DateTimeField(max_length=20,
                                       verbose_name='更新时间',
                                       auto_now=True)
    views = models.PositiveIntegerField('浏览量', default=0)
    subtopic_id = models.IntegerField(verbose_name='课程id')
    hint = models.TextField(blank=True, null=True)
    answer = models.TextField(blank=True, null=True)
    code = models.TextField(blank=True, null=True, verbose_name='骨架代码')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['update_date']  # 设定排序方式也可以以id来进行排序
        verbose_name = '课程'
        verbose_name_plural = verbose_name

courseApp/views.py
import os
import shutil
from django.db import connection
from django.db.models import Q, Count
from django.http.response import JsonResponse
from django.views.decorators.http import require_http_methods
from identity.models import Person
from .models import MyCourse, Topic
from identity.student_action_models import Like, Collect, History
import json
from datetime import date, datetime
from django.core import serializers  # JsonResponse用来将QuerySet序列化
from django.conf import settings
import uuid
global binlogEnd, binlogFile

"""
如果用JsonResponse处理上传日期需要对相应update_data进行处理
"""


class DateEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, datetime):
            return obj.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(obj, date):
            return obj.strftime('%Y-%m-%d')
        else:
            return json.JSONEncoder.default(self, obj)


"""
如果用JsonResponse处理MyCourse需要对整体进行处理
"""


class MyCourseEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, MyCourse):
            return obj.__str__()
        return json.JSONEncoder.default(self, obj)


"""
Done
还处于测试阶段并未成功插入page相关数据 因为不会处理在Json返回的报错
具体实现将数据库中符合条件的课程按创建时间升序排列
返回给前端嵌套的列表数据
"""


def search(request):
    if request.method == 'GET':
        keyword = request.GET.get('keyword')  # 获取关键词
        teacher_id = request.GET.get('teacher_id')
        if teacher_id:
            course_list = MyCourse.objects.filter(Q(title__icontains=keyword) & Q(related_topic__teacher_id=teacher_id))
        else:
            course_list = MyCourse.objects.filter(title__icontains=keyword)
        if len(course_list) > 0:
            course_list = serializers.serialize("json", course_list.order_by('update_date'))
            result = {
                "error_code": 200,
                "msg": 'success',
                'course_list': json.loads(course_list),
            }
            return JsonResponse(result, safe=False)
        else:
            result = {
                "error_code": 430,
                "msg": "the course does not exit",
            }
            return JsonResponse(result, status=430)
    else:
        result = {
            "error_code": 400,
            'msg': 'INVALID REQUEST'
        }
        return JsonResponse(result)


'''
Get topic on the Welcome page: (return the top 6 most valuable courses)
->GET:
<-
    [{
        'topic_title': Topic.topic_title,
        'topic_content': Topic.topic_content,
        'topic_img': Topic.topic_img,
    }, 
    {
        'topic_title': Topic.topic_title,
        'topic_content': Topic.topic_content,
        'topic_img': Topic.topic_img,
    }]
'''


@require_http_methods(["GET"])
def top_topic(request, num):
    all_topics = Topic.objects.filter().all()
    all_likes = Like.objects.all()
    all_collections = Collect.objects.all()
    score_dict = {}
    # print(all_topics.count())
    # compute the score for each topic
    for topic in all_topics:
        topic_score = 0
        topic_like = 0
        topic_collect = 0

        topic_create_time = topic.create_time.date()
        time_now = datetime.now().date()

        # Add up like score
        for like_obj in all_likes:
            if topic.topic_title == like_obj.topic.topic_title:
                topic_like += 1

        # Add up collect score
        for collect_obj in all_collections:
            if topic.topic_title == collect_obj.topic.topic_title:
                topic_collect += 1

        delta = time_now - topic_create_time
        topic_score += (topic_collect * 10 + topic_like * 5 + topic.views + 1) / \
                       ((delta.days + 3) ^ 2)  # Insure the denominator is not zero

        score_dict.update({topic.pk: topic_score})
        # print(str(score_dict))
    sorted_topic = dict(sorted(score_dict.items(), key=lambda item: item[1], reverse=True))

    # If num == "all", return all the topics ranked by heat
    if num == 'all':
        top_topics = []
        for key in sorted_topic.keys():
            top_topic = Topic.objects.get(pk=key)
            top_topic_img = ''
            if top_topic.topic_img:
                top_topic_img = str("/media/" + str(top_topic.topic_img))
            else:
                top_topic_img = None
            topic_dict = {
                "topic_title": top_topic.topic_title,
                "topic_content": top_topic.topic_description,
                "topic_img": top_topic_img
            }
            top_topics.append(topic_dict)
        return JsonResponse(top_topics, safe=False)

    # return number num of topics
    else:
        # add top num topics into a new dict
        required_cnt = int(num)
        cnt = 0
        top_6_dict = {}
        for key, value in sorted_topic.items():
            # print("key: " + str(key) + " value: " + str(value))
            cnt += 1
            if cnt > required_cnt:
                break
            top_6_dict.update({key: value})

        # search top 6 topic in database and add top 5 into a dict list
        top_6_list = []
        for key in top_6_dict.keys():
            top_6_topic = Topic.objects.get(pk=key)
            top_6_topic_img = ""
            if top_6_topic.topic_img:
                top_6_topic_img = str("/media/" + str(top_6_topic.topic_img))
                # str("http://120.26.46.74:4000/media/") + str(top_6_topic.topic_img)
            else:
                top_6_topic_img = None
            topic_dict = {
                "topic_title": top_6_topic.topic_title,
                "topic_content": top_6_topic.topic_description,
                "topic_img": top_6_topic_img
            }
            top_6_list.append(topic_dict)
        # print(top_5_list)
        return JsonResponse(top_6_list, safe=False)


'''
return newest courses sorted by date
-> Get
 [{
        'topic_title': Topic.topic_title,
        'topic_content': Topic.topic_content,
        'topic_img': Topic.topic_img,
    }, 
    {
        'topic_title': Topic.topic_title,
        'topic_content': Topic.topic_content,
        'topic_img': Topic.topic_img,
    }]

'''


def new_topic(request):
    if request.method == "GET":
        all_topics = Topic.objects.filter().all()
        create_date_dict = {}
        # Add all the topics into one date dict
        for topic in all_topics:
            topic_create_time = topic.create_time.date()
            create_date_dict.update({topic.pk: topic_create_time})
        # print(str(create_date_dict))

        # Sort the dict by the create time
        sorted_topic = dict(sorted(create_date_dict.items(), key=lambda item: item[1], reverse=True))
        # print(sorted_dict)
        # search newest topic in database and add sorted topics into a dict list
        new_topic_list = []
        for key in sorted_topic.keys():
            newest_topic = Topic.objects.get(pk=key)
            newest_topic_img = ""
            if newest_topic.topic_img:
                newest_topic_img = str("/media/" + str(newest_topic.topic_img))
                # str("http://120.26.46.74:4000/media/") + str(newest_topic.topic_img)
            else:
                newest_topic_img = None
            topic_dict = {
                "topic_title": newest_topic.topic_title,
                "topic_content": newest_topic.topic_description,
                "topic_img": newest_topic_img
            }
            new_topic_list.append(topic_dict)

        return JsonResponse(new_topic_list, safe=False)


'''
Search a related topic based on keyword
-> GET param: keyword
    
<- {
    "error_code": 200,
    "msg": "success",
    "search_title": "the result of searching" + keyword,
    'topic_list': [{topic_title: xxx},{topic_title: xxx}]
    }
'''


@require_http_methods(["GET"])
def binlog(request):
    global binlogEnd, binlogFile
    cursor = connection.cursor()
    cursor.execute("show master status")
    main_binlog_tuple = cursor.fetchall()
    # print(main_binlog_tuple)
    main_log = main_binlog_tuple[0][0]
    binlogFile = main_log
    # print(main_log)
    cursor.execute("show binlog events in '" + str(main_log) + "'")
    all_result = cursor.fetchall()
    raws = len(all_result)
    binlogEnd = raws
    last_modified_raw = 0
    results = []

    for i in range(0, raws):
        if all_result[raws - i - 1][5] == "BEGIN":
            last_modified_raw = i + 1
            # print("last_modified_raw: " + str(last_modified_raw))
            break

    for i in range(0, last_modified_raw):
        results.append(all_result[raws - i - 1])
    results.reverse()
    # print(list(results))
    response = {
        "binlog_file": results[0][0],
        "server_id": results[0][3],
        "begin_pos": results[0][1],
        "end_pos": results[len(results) - 1][4],
        "table": results[1][5],
        "operation": results[2][2],
        "flags": results[2][5]
    }
    # print(response)
    return JsonResponse(response)


@require_http_methods(["GET"])
def lastModifiedBinlog(request):
    global binlogEnd, binlogFile
    cursor = connection.cursor()
    cursor.execute("show binlog events in '" + str(binlogFile) + "'")
    all_result = cursor.fetchall()
    raws = len(all_result)
    # print("raws: " + str(raws) + " binlogEnd: " + str(binlogEnd))

    if raws <= binlogEnd:
        response = {
            "binlog_file": str(binlogFile),
            "result": "no change since last modify."
        }
        return JsonResponse(response)

    else:
        results = []
        for i in range(binlogEnd, raws):
            results.append(all_result[i])

        # print(list(results))

        modifications = {
        }

        single_modification = {
            "binlog_file": "",
            "server_id": "",
            "begin_pos": "",
            "end_pos": ""
        }
        time = 0
        for i in range(0, len(results)):

            if results[i][2] == "Anonymous_Gtid":
                # print("find begin!!!-------------")
                binlog_file = results[i][0]

courseApp/templates/courseList.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
{{topic_title}}
{% endblock %}

{% block content %}
<!-- <link href="http://cdn.bootcss.com/bootstrap/3.3.0/css/.css" rel="stylesheet"> -->

<div class="container-fluid">
    <div class="row">
        <!-- <img class="img-responsive model-img" src="{% static 'img/.jpg' %}"> -->
    </div>
</div>
<!-- 主体内容 -->
<div class="container">
    <div class="row row-3">
        <!-- 侧边导航栏 -->
        <div class="col-md-3">
            <div class="model-title">
                课程
            </div>
            <div class="model-list">
                <ul class="list-group">
                    <li class="list-group-item" id='basic'>
                        <a href="{% url 'courseApp:Courses' 'basic' %}">基础课程</a>
                    </li>
                    <li class="list-group-item" id='heigher'>
                        <a href="{% url 'courseApp:Courses' 'heigher' %}">高阶课程</a>
                    </li>
                    <li class="list-group-item" id='data'>
                        <a href="{% url 'courseApp:Courses' 'data' %}">数据分析</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- 说明文字和图片 -->
        <div class="col-md-9">
            <div class="model-details-title">
                {{topic_title}}
                <div class="col-md-7 hidden-xs model-details-title-search">
                    <form method="get" action="{% url 'haystack_search' %}">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="请输入关键词" required />
                            <span class="input-group-btn">
                                <input type="submit" class="btn btn-default" value="查询" />
                            </span>
                        </div>
                    </form>
                </div>
            </div>
            <div class="model-details">
                {% for mycourses in courseList %}
                <div class="courses-model">

                    <a href="{% url 'courseApp:coursesDetail' mycourses.id %}"><b>{{mycourses.title}}</b></a>
                    <span>【{{mycourses.update_date|date:"Y-m-d"}}】</span>
                    <p>
                        <!-- 添加课程简要说明 -->
                        {{mycourses.mytxt|truncatechars:"110"}}...
                    </p>
                </div>
                {% endfor %}

                {% if pageData %}
                <div class="paging">
                    <ul id="pages" class="pagination">
                        {% if pageData.first %}
                        <li><a href="?page=1">1</a></li>
                        {% endif %}
                        {% if pageData.left %}
                        {% if pageData.left_has_more %}
                        <li><span>...</span></li>
                        {% endif %}
                        {% for i in pageData.left %}
                        <li><a href="?page={{i}}">{{i}}</a></li>
                        {% endfor %}
                        {% endif %}
                        <li class="active"><a href="?page={{pageData.page}}">
                                {{pageData.page}}</a></li>
                        {% if pageData.right %}
                        {% for i in pageData.right %}
                        <li><a href="?page={{i}}">{{i}}</a></li>
                        {% endfor %}
                        {% if pageData.right_has_more %}
                        <li><span>...</span></li>
                        {% endif %}
                        {% endif %}
                        {% if pageData.last %}
                        <li><a href="?page={{pageData.total_pages}}">
                                {{pageData.total_pages}}</a></li>
                        {% endif %}
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}